---
abstract: 'Rose::DB::Object Cache using the CHI interface'
author:
  - 'Kevin C. McGrath (kmcgrath@baknet.com)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rose-DBx-Object-Cached-CHI
no_index:
  directory:
    - t
    - inc
requires:
  CHI: 0.26
  Rose::DB::Object: 0.782
  Test::Simple: 0.44
resources:
  repository: https://github.com/kmcgrath/Rose-DBx-Object-Cached-CHI
version: 0.22
