--- #YAML:1.0
name:               Rose-DBx-Object-Cached-CHI
version:            0.19
abstract:           Rose::DB::Object Cache using the CHI interface
author:
    - Kevin C. McGrath (kmcgrath@baknet.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CHI:               0.26
    Rose::DB::Object:  0.782
    Test::Simple:      0.44
resources:
    repository:  https://github.com/kmcgrath/Rose-DBx-Object-Cached-CHI
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
